#!/usr/bin/env python3
"""Generate a target repo's docs/PALETTE_CONTRAST_AUDIT.md from evidence.

Runs color extraction over an input tree, audits the palette against a target
WCAG contrast ratio, and renders the per-repo audit file: a title, a one-line
provenance note (generating skill, target ratio, background), and the audit
table built only from this run's extraction output. The generic WCAG method
doc (docs/COLOR_CONTRAST_ACCESSIBILITY.md) is propagated read-only from
starter-repo-template and assumed present; this script never writes it.

The only data inputs are the input tree and this run's extraction results. When
extraction finds zero colors, nothing is written: a colorless repo carries no
audit file.
"""

# Standard Library
import os
import argparse

# local repo modules
import color_utils
import audit_palette
import extract_colors

# name of the skill that owns and generates the audit file
SKILL_NAME = 'color-accessibility-expert'
# title of the generated per-repo audit file
AUDIT_TITLE = '# Palette contrast audit'

#============================================
def relative_base(source_root: str) -> str:
	"""Pick the directory that source-file paths are reported relative to.

	Args:
		source_root: Absolute path of the input file or directory.

	Returns:
		The directory used as the base for relative source paths.
	"""
	if os.path.isdir(source_root):
		return source_root
	# a single input file reports paths relative to its containing directory
	base = os.path.dirname(source_root)
	return base

#============================================
def collect_distinct_pairs(file_paths: list, rel_base: str) -> tuple:
	"""Collect distinct (source_file, hex) pairs from color extraction.

	Args:
		file_paths: List of files to scan.
		rel_base: Directory that source paths are reported relative to.

	Returns:
		Tuple of (sorted list of (source_file, hex) pairs, total hit count).
	"""
	distinct_pairs = set()
	total_hits = 0
	for hex_value, file_path, _line_number in extract_colors.iter_color_hits(file_paths):
		total_hits += 1
		# report file paths only, relative to the input root, so the committed
		# doc stays stable as files grow; line numbers stay in terminal output
		rel_path = os.path.relpath(file_path, rel_base)
		distinct_pairs.add((rel_path, hex_value))
	sorted_pairs = sorted(distinct_pairs)
	return sorted_pairs, total_hits

#============================================
def render_provenance(target_ratio: float, bg_hex: str) -> str:
	"""Render the one-line provenance note for the audit file.

	Args:
		target_ratio: Target contrast ratio used to classify pass/fail.
		bg_hex: Normalized background hex color the ratios are measured against.

	Returns:
		A single-line provenance sentence naming the generating skill, the
		target ratio, and the background.
	"""
	ratio_str = f"{target_ratio:.1f}:1"
	# one line: who generated this, at what target, against which background,
	# and where the generic WCAG method lives
	note = (
		f"Generated by the {SKILL_NAME} skill from this run's evidence, "
		f"measured against background `{bg_hex}` at a target of {ratio_str}. "
		f"For the WCAG contrast method, see the propagated "
		f"`docs/COLOR_CONTRAST_ACCESSIBILITY.md`."
	)
	return note

#============================================
def render_audit_table(results: list, target_ratio: float) -> str:
	"""Render the audit table from audit results.

	Args:
		results: Audit result dicts from audit_palette.audit_colors.
		target_ratio: Target contrast ratio used to classify pass/fail.

	Returns:
		The audit table text, header row through the last data row.
	"""
	table_lines = []
	table_lines.append('| Source file | Hex | Ratio vs background | Status |')
	table_lines.append('| --- | --- | --- | --- |')
	for result in results:
		ratio_str = f"{result['old_ratio']:.2f}:1"
		# a color at or above the target passes; otherwise report the darkened
		# replacement suggested by the audit and its improved ratio
		if result['old_ratio'] >= target_ratio:
			status = 'PASS'
		else:
			new_ratio_str = f"{result['new_ratio']:.2f}:1"
			status = f"FAIL -- suggested replacement {result['new_hex']} ({new_ratio_str})"
		row = (
			f"| {result['label']} | {result['old_hex']} | "
			f"{ratio_str} | {status} |"
		)
		table_lines.append(row)
	table = '\n'.join(table_lines)
	return table

#============================================
def render_audit_file(provenance: str, table: str) -> str:
	"""Assemble the full audit file text.

	Args:
		provenance: One-line provenance note from render_provenance.
		table: Audit table text from render_audit_table.

	Returns:
		The audit file text with a single trailing newline.
	"""
	doc_lines = []
	doc_lines.append(AUDIT_TITLE)
	doc_lines.append('')
	doc_lines.append(provenance)
	doc_lines.append('')
	doc_lines.append('## Palette audit')
	doc_lines.append('')
	doc_lines.append(table)
	doc_text = '\n'.join(doc_lines).rstrip('\n') + '\n'
	return doc_text

#============================================
def build_manifest(source_root: str, scanned_files: int,
		colors_found: int, colors_documented: int) -> str:
	"""Build the evidence manifest block printed after the run.

	Args:
		source_root: Absolute path of the input tree.
		scanned_files: Number of text files scanned.
		colors_found: Total color hits found during extraction.
		colors_documented: Number of distinct rows written to the audit table.

	Returns:
		The manifest text block.
	"""
	# the directory skip config that governs which subtrees extraction ignores
	skip_names = list(extract_colors.SKIP_DIR_NAMES)
	skip_prefixes = [f"{prefix}*" for prefix in extract_colors.SKIP_DIR_PREFIXES]
	skipped_dirs = ','.join(skip_names + skip_prefixes)
	manifest_lines = []
	manifest_lines.append('EVIDENCE')
	manifest_lines.append(f"source_root={source_root}")
	manifest_lines.append(f"scanned_files={scanned_files}")
	manifest_lines.append(f"skipped_dirs={skipped_dirs}")
	manifest_lines.append(f"colors_found={colors_found}")
	manifest_lines.append(f"colors_documented={colors_documented}")
	manifest = '\n'.join(manifest_lines)
	return manifest

#============================================
def parse_args() -> argparse.Namespace:
	"""Parse command-line arguments."""
	parser = argparse.ArgumentParser(
		description="Generate a repo's PALETTE_CONTRAST_AUDIT.md from evidence"
	)
	parser.add_argument(
		'-i', '--input', dest='input_path', type=str, required=True,
		help='Target repo root or subtree to scan for color literals'
	)
	parser.add_argument(
		'-o', '--output', dest='output_file', type=str, default=None,
		help='Output doc path (default: docs/PALETTE_CONTRAST_AUDIT.md '
			'under the input root)'
	)
	parser.add_argument(
		'-b', '--background', dest='bg_hex', type=str, default='#ffffff',
		help='Background hex color (default: #ffffff)'
	)
	parser.add_argument(
		'-r', '--ratio', dest='target_ratio', type=float, default=5.5,
		help='Target contrast ratio (default: 5.5)'
	)
	args = parser.parse_args()
	return args

#============================================
def main() -> None:
	"""Main entry point."""
	args = parse_args()

	source_root = os.path.abspath(args.input_path)
	rel_base = relative_base(source_root)

	# resolve the default output path under the input root when none was given
	if args.output_file:
		output_file = os.path.abspath(args.output_file)
	else:
		output_file = os.path.join(rel_base, 'docs', 'PALETTE_CONTRAST_AUDIT.md')

	# extract color literals from the input tree
	file_paths = extract_colors.gather_text_files([source_root])
	sorted_pairs, colors_found = collect_distinct_pairs(file_paths, rel_base)
	colors_documented = len(sorted_pairs)

	# a colorless repo carries no audit file: write nothing and say so
	if not sorted_pairs:
		manifest = build_manifest(
			source_root, len(file_paths), colors_found, colors_documented
		)
		print(f"No color literals found under {source_root}; no audit file written.")
		print(manifest)
		return

	# audit the distinct pairs against the background and render the audit file
	bg_hex = color_utils.parse_color_token(args.bg_hex)
	entries = [(rel_path, hex_value) for rel_path, hex_value in sorted_pairs]
	results = audit_palette.audit_colors(
		entries, args.target_ratio, bg_hex, normalize=False
	)
	provenance = render_provenance(args.target_ratio, bg_hex)
	table = render_audit_table(results, args.target_ratio)
	doc_text = render_audit_file(provenance, table)

	# write the audit file, creating the output directory as needed
	output_dir = os.path.dirname(output_file)
	if output_dir:
		os.makedirs(output_dir, exist_ok=True)
	with open(output_file, 'w', encoding='utf-8') as handle:
		handle.write(doc_text)

	# print the evidence manifest to stdout after writing the doc
	manifest = build_manifest(
		source_root, len(file_paths), colors_found, colors_documented
	)
	print(manifest)

#============================================
if __name__ == '__main__':
	main()
