#!/usr/bin/env python3
"""Build the searchable agent index from canonical catalog data."""

from __future__ import annotations

# Standard Library
import argparse
import pathlib
import subprocess

# local repo modules
import install_lib.agent_catalog


INDEX_PATH = pathlib.Path("docs/AGENTS_INDEX.md")


#============================================
def render_agents_index(agents: list[dict]) -> str:
	"""Render concise searchable agent metadata with links to authored sources."""
	lines = [
		"<!-- Generated by tools/build_agents_index.py from agents/CATALOG.yaml. -->",
		"",
		"# Agent index",
		"",
		"Canonical agent instructions live in [agents/](../agents/). This index makes their roles,",
		"authority boundaries, and escalation routes searchable without duplicating instruction bodies.",
		"",
		"| Agent | Category | Gas Town role | Access | Authority boundary | Escalation routes |",
		"| --- | --- | --- | --- | --- | --- |",
	]
	for entry in agents:
		routes = "<br>".join(entry["escalation_routes"]) or "--"
		lines.append(
			f"| [agents/{entry['id']}.md](../agents/{entry['id']}.md) | {entry['category']} | "
			f"{entry['gas_town_role']} | {entry['access']} | {entry['authority_boundary']} | "
			f"{routes} |"
		)
	lines.append("")
	return "\n".join(lines)


#============================================
def write_or_check_index(repo_root: pathlib.Path, check: bool) -> None:
	"""Write the agent index or validate it against current canonical data."""
	path = repo_root / INDEX_PATH
	expected = render_agents_index(install_lib.agent_catalog.load_agents(repo_root))
	if check:
		if not path.is_file() or path.read_text(encoding="utf-8") != expected:
			raise ValueError(f"Agent index is stale: {path.as_posix()}")
		return
	path.write_text(expected, encoding="utf-8")


#============================================
def get_repo_root() -> pathlib.Path:
	"""Return the repository root from Git's authoritative worktree lookup."""
	result = subprocess.run(
		["git", "rev-parse", "--show-toplevel"],
		cwd=pathlib.Path(__file__).resolve().parent,
		check=False,
		capture_output=True,
		text=True,
	)
	if result.returncode != 0:
		error_text = result.stderr.strip()
		raise RuntimeError(f"Could not determine repository root: {error_text}")
	return pathlib.Path(result.stdout.strip())


#============================================
def parse_args() -> argparse.Namespace:
	"""Parse the optional stale-output check mode."""
	parser = argparse.ArgumentParser(description=__doc__)
	parser.add_argument("--check", action="store_true", help="report stale agent index output")
	args = parser.parse_args()
	return args


#============================================
def main() -> None:
	"""Build or validate the agent index at the repository root."""
	args = parse_args()
	repo_root = get_repo_root()
	write_or_check_index(repo_root, args.check)


if __name__ == "__main__":
	main()
